### ISSUE TITLE
Json errors

### ISSUE THREAD

**Issue by 10kmotorola** [JohnKuruvila/qbittorrent-peers-location-grafana#1]
Probably just me being a python newbie, but I get this error when running the script:
```
orchid@server:~$ python3 qbittorrent_peers_location_grafana.py 
Traceback (most recent call last):
  File "/home/orchid/qbittorrent_peers_location_grafana.py", line 23, in <module>
    torrents = json.loads(s.get(server_address + "/api/v2/torrents/info").text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Here's my .py file, if it helps (with sensitive info masked obv):
```
orchid@server:~$ cat qbittorrent_peers_location_grafana.py 
import requests
import json
import socket, struct
import mariadb 
import time
import pygeohash

#To convert the IP address in xxx.xxx.xxx.xxx to a decimal number
def ip2long(ip):
    packedIP = socket.inet_aton(ip)
    return struct.unpack("!L", packedIP)[0]

#qbittorrent credentials
server_ip = "localhost"
qbport = "[PORT]"
qbusername = "[USERNAME]"
qbpassword = "[PASSWORD]"

server_address = "http://" + server_ip + ":" + qbport

s = requests.Session()
s.get(server_address + "/api/v2/auth/login?username=" + qbusername + "&password=" + qbpassword)
torrents = json.loads(s.get(server_address + "/api/v2/torrents/info").text)

#Logging into mariadb server / Enter your mariadb credentials here
mydb = mariadb.connect(
          host="localhost",
          port=[PORT],
          user="[USER]",
          password="[PASSWORD]",
          database="ip2location",
          autocommit=True
)

current_time = str(int(time.time())) 

for torrent in torrents:
    torrent_peers = json.loads(s.get(server_address + "/api/v2/sync/torrentPeers?hash=" + torrent["hash"]).text)

    #Get IP address of every peer of every torrent
    for peer in torrent_peers["peers"]:
        ip = peer.split(":")[0]
        long_ip = ip2long(ip)

        mycursor = mydb.cursor()

        query="SELECT latitude,longitude FROM ip2location.ip2location_db5 WHERE " + str(long_ip) + " BETWEEN ip_from AND ip_to;"
        mycursor.execute(query)
        results = mycursor.fetchall()[0]
        latitude = results[0]
        longitude = results[1]

        if latitude == 0 and longitude == 0:
            continue #Sometimes (especially in public trackers) some IP's in the private IP space show up as peers. This should filter those.

        geohash = pygeohash.encode(latitude, longitude)

        query = "INSERT INTO ip2location.peer_list(time, ip_address, geohash) VALUES (" + current_time + ",'" + str(ip) + "','" + geohash + "');"
        mycursor.execute(query)


s.get(server_address + "/api/v2/auth/logout")
```

**Comment by ghost** [comment]
Hi! Can you try adding this line of code before the `torrents = s.get(...` line?

`print(s.get(server_address + "/api/v2/torrents/info").text)`

Check if its outputting a proper JSON string.

**Comment by 10kmotorola** [comment]
Fastest response to an issue I've ever gotten lol, thanks!
```
orchid@server:~$ python3 qbittorrent_peers_location_grafana.py 
Forbidden
Traceback (most recent call last):
  File "/home/orchid/qbittorrent_peers_location_grafana.py", line 24, in <module>
    torrents = json.loads(s.get(server_address + "/api/v2/torrents/info").text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ghost** [comment]
Haha! No problem. It seems like there's some sort of issue in connecting to the qBittorrent web UI.

Navigate to the web UI on your browser, go to tools > options and then click on the Web UI tab. Try to see if there's any setting that might be causing issues.

If security is not a concern, you could just check the `Bypass authentication for clients on localhost` option.

**Comment by 10kmotorola** [comment]
Even with `Bypass authentication for clients on localhost` ticked on it still gives the same error. If it's of note, I'm running qBittorrent through Docker.

**Comment by ghost** [comment]
I was able to recreate the issue. Apparently the web API has been modified and a lot of GET requests have been changed to POST requests. See [#18097](https://github.com/qbittorrent/qBittorrent/issues/18097).

All you need to do is change this line

`s.get(server_address + "/api/v2/auth/login?username=" + qbusername + "&password=" + qbpassword)`

to this

`s.post(server_address + "/api/v2/auth/login", data = {"username": qbusername, "password" : qbpassword})`

Hope this helps! And thank you for bringing this to my attention. Admittedly, I haven't been running this script for a while and didn't know about the API changes. I'll push the changes ASAP :)

**Comment by 10kmotorola** [comment]
Worked perfectly. Thanks! :D
